### ISSUE TITLE
Where does cdnAssetPipelinePluginDir come from?

### ISSUE THREAD

**Issue by tedder** [agorapulse/grails-cdn-asset-pipeline#11]
Hi, I'm trying to modify the plugin- I'll send a PR back if I'm successful. But I'm having an error with cdnAssetPipelinePluginDir, which is in the scripts. Where does that come from? How is it/should it be set?

**Comment by benorama** [comment]
I can't remember... I guess it's provided by Gant script.
FYI, I've migrated this plugin to Gradle for Grails 3:
https://github.com/agorapulse/gradle-asset-pipeline-cdn

**Comment by tedder** [comment]
Hmm. I'm having a hell of a time using a local-override of this plugin. I was going to expand it to use role-based AWS auth, but it looks like Karman doesn't support it either.
