### ISSUE TITLE
assets are fetched without the hash code appended

### ISSUE THREAD

**Issue by florent-blanvillain** [agorapulse/grails-cdn-asset-pipeline#8]
Hello,

I configured this plugin on a nearly bare grails project to test it, simply following the docs, it happens that assets are uploaded (to s3 in my case) with an hash code appended https://s3-eu-west-1.amazonaws.com/provideup-dev-assets/assets/pride-design-0.1/common/common-f09ba8f30c4afd6d752128bad7e0e5ba.css but when I run my app either in dev or prod environment, it tries to fectch https://s3-eu-west-1.amazonaws.com/provideup-dev-assets/assets/pride-design-0.1/common/common.css.

Any idea why ? Maybe I'm missing something that could be added to the documentation ?

For the record, I'm using grails 2.4.3 with :

    compile ":asset-pipeline:1.9.9"
    compile ':cdn-asset-pipeline:0.3.5'

Florent.

**Comment by dennisdrew** [comment]
I am also experiencing this issue after running prod run-app and prod run-war.

**Comment by dennisdrew** [comment]
For some reason, I now got it to work using run-war. Perhaps I had only tried prod run-app, but not run-war.

Anyway, run-war works for my needs and adds the hash to the asset names.

Thanks!

**Comment by parasjain** [comment]
I am also experiencing this issue after running prod run-app and prod run-war. 
Has there been any workaround for this issue?

**Comment by benorama** [comment]
This behaviour is not linked to this plugin but to the Asset Pipeline Plugin: https://github.com/bertramdev/asset-pipeline
You might post your issue there.
